# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/shashwat/Desktop/GITCLONE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/shashwat/Desktop/GITCLONE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shashwat/Desktop/GITCLONE/CMakeFiles /home/shashwat/Desktop/GITCLONE//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shashwat/Desktop/GITCLONE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named git_c

# Build rule for target.
git_c: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 git_c
.PHONY : git_c

# fast build rule for target.
git_c/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git_c.dir/build.make CMakeFiles/git_c.dir/build
.PHONY : git_c/fast

src/CPP/cat_file.o: src/CPP/cat_file.cpp.o
.PHONY : src/CPP/cat_file.o

# target to build an object file
src/CPP/cat_file.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git_c.dir/build.make CMakeFiles/git_c.dir/src/CPP/cat_file.cpp.o
.PHONY : src/CPP/cat_file.cpp.o

src/CPP/cat_file.i: src/CPP/cat_file.cpp.i
.PHONY : src/CPP/cat_file.i

# target to preprocess a source file
src/CPP/cat_file.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git_c.dir/build.make CMakeFiles/git_c.dir/src/CPP/cat_file.cpp.i
.PHONY : src/CPP/cat_file.cpp.i

src/CPP/cat_file.s: src/CPP/cat_file.cpp.s
.PHONY : src/CPP/cat_file.s

# target to generate assembly for a file
src/CPP/cat_file.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git_c.dir/build.make CMakeFiles/git_c.dir/src/CPP/cat_file.cpp.s
.PHONY : src/CPP/cat_file.cpp.s

src/CPP/git_add.o: src/CPP/git_add.cpp.o
.PHONY : src/CPP/git_add.o

# target to build an object file
src/CPP/git_add.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git_c.dir/build.make CMakeFiles/git_c.dir/src/CPP/git_add.cpp.o
.PHONY : src/CPP/git_add.cpp.o

src/CPP/git_add.i: src/CPP/git_add.cpp.i
.PHONY : src/CPP/git_add.i

# target to preprocess a source file
src/CPP/git_add.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git_c.dir/build.make CMakeFiles/git_c.dir/src/CPP/git_add.cpp.i
.PHONY : src/CPP/git_add.cpp.i

src/CPP/git_add.s: src/CPP/git_add.cpp.s
.PHONY : src/CPP/git_add.s

# target to generate assembly for a file
src/CPP/git_add.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git_c.dir/build.make CMakeFiles/git_c.dir/src/CPP/git_add.cpp.s
.PHONY : src/CPP/git_add.cpp.s

src/CPP/git_init.o: src/CPP/git_init.cpp.o
.PHONY : src/CPP/git_init.o

# target to build an object file
src/CPP/git_init.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git_c.dir/build.make CMakeFiles/git_c.dir/src/CPP/git_init.cpp.o
.PHONY : src/CPP/git_init.cpp.o

src/CPP/git_init.i: src/CPP/git_init.cpp.i
.PHONY : src/CPP/git_init.i

# target to preprocess a source file
src/CPP/git_init.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git_c.dir/build.make CMakeFiles/git_c.dir/src/CPP/git_init.cpp.i
.PHONY : src/CPP/git_init.cpp.i

src/CPP/git_init.s: src/CPP/git_init.cpp.s
.PHONY : src/CPP/git_init.s

# target to generate assembly for a file
src/CPP/git_init.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git_c.dir/build.make CMakeFiles/git_c.dir/src/CPP/git_init.cpp.s
.PHONY : src/CPP/git_init.cpp.s

src/CPP/hash_object.o: src/CPP/hash_object.cpp.o
.PHONY : src/CPP/hash_object.o

# target to build an object file
src/CPP/hash_object.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git_c.dir/build.make CMakeFiles/git_c.dir/src/CPP/hash_object.cpp.o
.PHONY : src/CPP/hash_object.cpp.o

src/CPP/hash_object.i: src/CPP/hash_object.cpp.i
.PHONY : src/CPP/hash_object.i

# target to preprocess a source file
src/CPP/hash_object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git_c.dir/build.make CMakeFiles/git_c.dir/src/CPP/hash_object.cpp.i
.PHONY : src/CPP/hash_object.cpp.i

src/CPP/hash_object.s: src/CPP/hash_object.cpp.s
.PHONY : src/CPP/hash_object.s

# target to generate assembly for a file
src/CPP/hash_object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git_c.dir/build.make CMakeFiles/git_c.dir/src/CPP/hash_object.cpp.s
.PHONY : src/CPP/hash_object.cpp.s

src/CPP/ls_tree.o: src/CPP/ls_tree.cpp.o
.PHONY : src/CPP/ls_tree.o

# target to build an object file
src/CPP/ls_tree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git_c.dir/build.make CMakeFiles/git_c.dir/src/CPP/ls_tree.cpp.o
.PHONY : src/CPP/ls_tree.cpp.o

src/CPP/ls_tree.i: src/CPP/ls_tree.cpp.i
.PHONY : src/CPP/ls_tree.i

# target to preprocess a source file
src/CPP/ls_tree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git_c.dir/build.make CMakeFiles/git_c.dir/src/CPP/ls_tree.cpp.i
.PHONY : src/CPP/ls_tree.cpp.i

src/CPP/ls_tree.s: src/CPP/ls_tree.cpp.s
.PHONY : src/CPP/ls_tree.s

# target to generate assembly for a file
src/CPP/ls_tree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git_c.dir/build.make CMakeFiles/git_c.dir/src/CPP/ls_tree.cpp.s
.PHONY : src/CPP/ls_tree.cpp.s

src/CPP/main.o: src/CPP/main.cpp.o
.PHONY : src/CPP/main.o

# target to build an object file
src/CPP/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git_c.dir/build.make CMakeFiles/git_c.dir/src/CPP/main.cpp.o
.PHONY : src/CPP/main.cpp.o

src/CPP/main.i: src/CPP/main.cpp.i
.PHONY : src/CPP/main.i

# target to preprocess a source file
src/CPP/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git_c.dir/build.make CMakeFiles/git_c.dir/src/CPP/main.cpp.i
.PHONY : src/CPP/main.cpp.i

src/CPP/main.s: src/CPP/main.cpp.s
.PHONY : src/CPP/main.s

# target to generate assembly for a file
src/CPP/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git_c.dir/build.make CMakeFiles/git_c.dir/src/CPP/main.cpp.s
.PHONY : src/CPP/main.cpp.s

src/CPP/utils.o: src/CPP/utils.cpp.o
.PHONY : src/CPP/utils.o

# target to build an object file
src/CPP/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git_c.dir/build.make CMakeFiles/git_c.dir/src/CPP/utils.cpp.o
.PHONY : src/CPP/utils.cpp.o

src/CPP/utils.i: src/CPP/utils.cpp.i
.PHONY : src/CPP/utils.i

# target to preprocess a source file
src/CPP/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git_c.dir/build.make CMakeFiles/git_c.dir/src/CPP/utils.cpp.i
.PHONY : src/CPP/utils.cpp.i

src/CPP/utils.s: src/CPP/utils.cpp.s
.PHONY : src/CPP/utils.s

# target to generate assembly for a file
src/CPP/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git_c.dir/build.make CMakeFiles/git_c.dir/src/CPP/utils.cpp.s
.PHONY : src/CPP/utils.cpp.s

src/CPP/write_tree.o: src/CPP/write_tree.cpp.o
.PHONY : src/CPP/write_tree.o

# target to build an object file
src/CPP/write_tree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git_c.dir/build.make CMakeFiles/git_c.dir/src/CPP/write_tree.cpp.o
.PHONY : src/CPP/write_tree.cpp.o

src/CPP/write_tree.i: src/CPP/write_tree.cpp.i
.PHONY : src/CPP/write_tree.i

# target to preprocess a source file
src/CPP/write_tree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git_c.dir/build.make CMakeFiles/git_c.dir/src/CPP/write_tree.cpp.i
.PHONY : src/CPP/write_tree.cpp.i

src/CPP/write_tree.s: src/CPP/write_tree.cpp.s
.PHONY : src/CPP/write_tree.s

# target to generate assembly for a file
src/CPP/write_tree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/git_c.dir/build.make CMakeFiles/git_c.dir/src/CPP/write_tree.cpp.s
.PHONY : src/CPP/write_tree.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... git_c"
	@echo "... src/CPP/cat_file.o"
	@echo "... src/CPP/cat_file.i"
	@echo "... src/CPP/cat_file.s"
	@echo "... src/CPP/git_add.o"
	@echo "... src/CPP/git_add.i"
	@echo "... src/CPP/git_add.s"
	@echo "... src/CPP/git_init.o"
	@echo "... src/CPP/git_init.i"
	@echo "... src/CPP/git_init.s"
	@echo "... src/CPP/hash_object.o"
	@echo "... src/CPP/hash_object.i"
	@echo "... src/CPP/hash_object.s"
	@echo "... src/CPP/ls_tree.o"
	@echo "... src/CPP/ls_tree.i"
	@echo "... src/CPP/ls_tree.s"
	@echo "... src/CPP/main.o"
	@echo "... src/CPP/main.i"
	@echo "... src/CPP/main.s"
	@echo "... src/CPP/utils.o"
	@echo "... src/CPP/utils.i"
	@echo "... src/CPP/utils.s"
	@echo "... src/CPP/write_tree.o"
	@echo "... src/CPP/write_tree.i"
	@echo "... src/CPP/write_tree.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

