name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag git_2.0:$(date +%s)

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag git_2.0:$(date +%s) ${{ secrets.DOCKERHUB_USERNAME }}/git_2.0:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/git_2.0:latest
