name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # Sets up Docker Buildx for multi-platform builds

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag docker.pkg.github.com/${{ github.repository_owner }}/${{ github.repository }}/git_2.0:$(date +%s)

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.repository_owner }} --password-stdin

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push docker.pkg.github.com/${{ github.repository_owner }}/${{ github.repository }}/git_2.0:latest
