name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # Sets up Docker Buildx for multi-platform builds

      - name: Build the Docker image
        run: |
          IMAGE_TAG=$(date +%s)
          # Convert GitHub username and repository name to lowercase
          GITHUB_USERNAME=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPOSITORY_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          REPOSITORY_URL="docker.pkg.github.com/${GITHUB_USERNAME}/${REPOSITORY_NAME}/git_2.0"
          docker build . --file Dockerfile --tag $REPOSITORY_URL:$IMAGE_TAG

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.repository_owner }} --password-stdin

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push $REPOSITORY_URL:latest
